
clean:

module: TKAuthorityModule
module_version: 0.1.0
root_url: https://github.com/zhuamaodeyu/
author: 抓猫的鱼
author_url: https://github.com/zhuamaodeyu/knowledge
github_url: https://github.com/zhuamaodeyu/TKAuthorityModule.git

title: TKComponentization/TKAuthorityModule 
readme: ../README.md


theme: apple
output: out/doc


copyright: '© 2018 [抓猫的鱼](https://github.com/zhuamaodeyu/knowledge) under
[open source license](https://github.com/zhuamaodeyu/TKAuthorityModule/blob/master/LICENSE).'


# xcodebuild arguments
# xcodebuild_arguments: ["-workspace","TKAuthorityModule.xcworkspace",
#                         "-scheme","TKAuthorityModule","-sdk","iphonesimulator"]

xcodebuild_arguments:
- -workspace
- TKAuthorityModule.xcworkspace
- -scheme
- TKAuthorityModule
- -sdk
- iphonesimulator


hide_documentation_coverage: true
documentation: ../*.md  # 都可
skip_undocumented: true


# docset
# docset-icon: xxxx/xxx
# docset-path: xxx/xxx


swift_version: 5.0.1
min_acl: public # public open, fileprivate, intxxx

# exclude:
# - "xxxxx.swift"
# - "xxxx.swift"


custom_categories:

- name: Protocol
  children:
  - AuthorityProtocol

- name: Manager
  children:
  - AuthorityManager 

- name: Enum 
  children:  
  - TouchIDAuthority
  - LocaltionType


